name: "Customize x86-64"
runs:
  using: "composite"
  steps:
    - name: Customize x86-64
      working-directory: ./openwrt
      shell: bash
      run: |
        cat >> ./.config <<EOF
        # CONFIG_VHDX_IMAGES=y
        # CONFIG_GRUB_EFI_IMAGES=y
        # CONFIG_TARGET_IMAGES_GZIP=n
        CONFIG_TARGET_ROOTFS_EXT4FS=y
        CONFIG_TARGET_ROOTFS_TARGZ=n
        CONFIG_TARGET_ROOTFS_SQUASHFS=n
        # CONFIG_TARGET_ROOTFS_PARTSIZE=1024
        # CONFIG_TARGET_KERNEL_PARTSIZE=16
        # CONFIG_TARGET_EXT4_BLOCKSIZE_4K=y
        # CONFIG_TARGET_EXT4_BLOCKSIZE=4096
        EOF

        mkdir -p ./files/etc/uci-defaults
        mkdir -p ./files/usr/bin
        wget -qO /tmp/gost.tar.gz $(curl -s https://api.github.com/repos/go-gost/gost/releases/latest | jq -r '.assets[].browser_download_url' | grep linux_amd64v3)
        tar xzf /tmp/gost.tar.gz -C /tmp
        mv /tmp/gost ./files/usr/bin/gost
        echo chmod +x /usr/bin/gost > ./files/etc/uci-defaults/99-gost

        # wget -qO $(ls -d ./target/linux/x86/patches-*)/600-bnx2x-warpcore-8727-2g5.patch https://raw.githubusercontent.com/JAMESMTL/snippets/master/bnx2x/patches/bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch

        sed -i '/DEFAULT:=n/d' ./feeds/packages/net/rp-pppoe/Makefile
        # sed -i 's/LOG info "Check/#LOG info "Check/' ./feeds/packages/net/mwan3/files/usr/sbin/mwan3track

        # git clone https://github.com/khrozelfist/3proxy-openwrt ./package/3proxy
        # ./scripts/feeds install 3proxy

        # rm -rf ./feeds/packages/net/smartdns
        # rm -rf ./feeds/luci/applications/luci-app-smartdns
        # git clone https://github.com/pymumu/openwrt-smartdns ./feeds/packages/net/smartdns
        # git clone https://github.com/pymumu/luci-app-smartdns ./feeds/luci/applications/luci-app-smartdns/
