name: "Deliver artifact"
runs:
  using: "composite"
  steps:
    - name: Prepare artifact
      shell: bash
      run : |
        [ -f ./artifact/buildinfo/config.ib ] && MAIN=openwrt-imagebuilder
        [ -f ./artifact/buildinfo/config.ib ] || MAIN=openwrt

        INFO=$(find ./$MAIN/bin/targets/ -type f ! -size +5M ! -path "*/packages*")
        [ "$INFO" ] && cp -rf $INFO ./artifact/buildinfo/
        find ./$MAIN/bin/targets/ -path "*/packages" -prune -o -type f -printf "%p %s\n" >./artifact/buildinfo/targets.output
        find ./openwrt/bin/ -type f -regex '.*\.\(ipk\|apk\)$' >./artifact/buildinfo/packages.${{env.mode}}
        find ./openwrt/ >./artifact/buildinfo/files.${{env.mode}}
        find ./openwrt-imagebuilder/ >./artifact/buildinfo/files.ib

        mkdir -p ./openwrt/bin/packages
        rm -rf ./openwrt/bin/packages/*/base
        mv -f ./openwrt/bin/packages ./artifact/package
        # PKG=$(find ./openwrt/bin/packages/ -type f -regex '.*\.\(ipk\|apk\)$')
        # [ "$PKG" ] && cp -rf $PKG ./artifact/package/

        # cp -rf $(find ./$MAIN/bin/targets/ -type f) ./artifact/firmware/
        # rm -rf $(find ./artifact/firmware/ -type f -name "*.bin")
        # rm -rf $(find ./artifact/firmware/ -type f -name "*.tar.gz")
        # rm -rf $(find ./artifact/firmware/ -type f -name "*.img*" | grep -v "combined-efi")

    - name: Deliver buildinfo
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_buildinfo_${{env.tag}}_${{env.date}}
        path: ./artifact/buildinfo/

    - name: Deliver package
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_package_${{env.tag}}_${{env.date}}
        path: ./artifact/package/

    - name: Deliver firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware_${{env.tag}}_${{env.date}}
        path: ./artifact/firmware/
