name: "Prepare Files"
runs:
  using: "composite"
  steps:
      working-directory: ./openwrt
      shell: bash
      run : |
        git checkout ${{env.tag}}
        sed -i '/DEFAULT:=n/d' ./feeds/packages/net/rp-pppoe/Makefile
        # sed -i 's/LOG info "Check/#LOG info "Check/' ./feeds/packages/net/mwan3/files/usr/sbin/mwan3track

        mkdir -p ./files/etc/uci-defaults
        mkdir -p ./files/usr/bin
        gostver=$(curl -s https://api.github.com/repos/go-gost/gost/releases/latest | jq -r '.tag_name' | sed 's/^v//')
        curl -Lso /tmp/gost.tar.gz https://github.com/go-gost/gost/releases/download/v${gostver}/gost_${gostver}_linux_amd64v3.tar.gz
        tar xzf /tmp/gost.tar.gz -C /tmp
        mv /tmp/gost ./files/usr/bin/gost
        echo chmod +x /usr/bin/gost > ./files/etc/uci-defaults/99-gost
