name: "Prepare Buildroot"
inputs:
  mode:
    required: false
    default: "full"
  target:
    required: false
    default: "x86/64"
runs:
  using: "composite"
  steps:
    - name: Prepare Buildroot
      shell: bash
      run : |
        echo "mode=${{inputs.mode}}" >> $GITHUB_ENV
        echo "target=${{inputs.target}}" >> $GITHUB_ENV
        echo "board=$(echo ${{inputs.target}} | awk -F / '{print$1}')" >> $GITHUB_ENV
        echo "subtarget=$(echo ${{inputs.target}} | awk -F / '{print$2}')" >> $GITHUB_ENV

        if [ ${{inputs.mode}} == full ]; then
          git clone https://github.com/openwrt/openwrt.git
          cd openwrt
          git checkout ${{env.tag}}
        elif [ ${{inputs.mode}} == sdk ]; then
          SDK=$(curl -s https://downloads.openwrt.org/releases/${{env.ver}}/targets/${{inputs.target}}/ | grep -oP 'href="\Kopenwrt-sdk-${{env.ver}}[^"]*"' | tr -d '"')
          wget -q https://downloads.openwrt.org/releases/${{env.ver}}/targets/${{inputs.target}}/$SDK
          mkdir -p openwrt
          tar --zstd -xf openwrt-sdk-*.tar.zst -C openwrt --strip-components=1
          cd openwrt
        else
          echo Wrong mode >&2 && exit 1
        fi

        rm -f ./.config
        curl -Ls https://downloads.openwrt.org/releases/${{env.ver}}/targets/${{inputs.target}}/config.buildinfo | grep -e CONFIG_TARGET_ -e CONFIG_KERNEL_ -e CONFIG_PACKAGE_ -e CONFIG_VERSION_ >> ./.config
        sed -i 's/CONFIG_TARGET_MULTI_PROFILE=y/CONFIG_TARGET_MULTI_PROFILE=n/' ./.config
        sed -i 's/CONFIG_TARGET_PER_DEVICE_ROOTFS=y/CONFIG_TARGET_PER_DEVICE_ROOTFS=n/' ./.config
        sed -i 's/CONFIG_TARGET_ALL_PROFILES=y/CONFIG_TARGET_ALL_PROFILES=n/' ./.config

        # sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' ./feeds.conf.default
        sed -i 's|git.openwrt.org/openwrt/openwrt.git|github.com/openwrt/openwrt.git|' feeds.conf.default
        sed -i 's|git.openwrt.org/feed/packages.git|github.com/openwrt/packages.git|' feeds.conf.default
        sed -i 's|git.openwrt.org/project/luci.git|github.com/openwrt/luci.git|' feeds.conf.default
        sed -i 's|git.openwrt.org/feed/routing.git|github.com/openwrt/routing.git|' feeds.conf.default
        sed -i 's|git.openwrt.org/feed/telephony.git|github.com/openwrt/telephony.git|' feeds.conf.default

        ./scripts/feeds update -a

        ./scripts/feeds install -a
        # ./scripts/feeds install -a -f
