name: OpenWrt-CI-x86_64 (Test)

on:
  workflow_dispatch:

jobs:
  build_openwrt:
    name: Build OpenWrt firmware
    runs-on: ubuntu-latest
    steps:
#   - name: Test
#     run : |
#       read -p "pause"

    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        set +e
        docker rmi `docker images -q`
        sudo rm -rf \
          /usr/share/dotnet \
          /usr/local/lib/android \
          /opt/ghc \
          /etc/mysql \
          /etc/php
        sudo -E apt-get -y purge azure-cli* docker* ghc* zulu* hhvm* llvm* firefox* google* dotnet* aspnetcore* powershell* openjdk* adoptopenjdk* mysql* php* mongodb* moby* snap* || true
        sudo -E apt-get update
        sudo -E apt-get -y install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev qemu-img
        sudo -E apt-get -y autoremove --purge
        sudo -E apt-get clean

    - name: Git
      run : |
        git clone https://github.com/openwrt/openwrt.git
        cd openwrt
        TAG=$(git tag | sort | tail -1 | awk -F '-' '{print$1}')
        git tag | grep $TAG$ || TAG=$(git tag | sort | tail -1)
        echo "tag=$TAG" >> $GITHUB_ENV
        echo "date=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV

    - name: Pre-feeds
      working-directory: ./openwrt
      run: |
        git checkout ${{env.tag}}

        # sed -i '$a src-git smpackage https://github.com/kenzok8/small-package' ./feeds.conf.default
        # git clone https://github.com/khrozelfist/3proxy-openwrt ./package/3proxy
        # wget -O $(ls -d ./target/linux/x86/patches-*)/600-bnx2x-warpcore-8727-2g5.patch https://raw.githubusercontent.com/JAMESMTL/snippets/master/bnx2x/patches/bnx2x_warpcore_8727_2_5g_sgmii_txfault.patch

    - name: Update & Install feeds
      working-directory: ./openwrt
      run : |
        git checkout ${{env.tag}}
        # sed -i 's|https://git.openwrt.org/feed/packages.git|https://github.com/openwrt/packages.git|' feeds.conf.default
        # sed -i 's|https://git.openwrt.org/project/luci.git|https://github.com/openwrt/luci.git|' feeds.conf.default
        # sed -i 's|https://git.openwrt.org/feed/routing.git|https://github.com/openwrt/routing.git|' feeds.conf.default
        # sed -i 's|https://git.openwrt.org/feed/telephony.git|https://github.com/openwrt/telephony.git|' feeds.conf.default

        ./scripts/feeds update -a

        rm -rf ./feeds/packages/net/smartdns
        rm -rf ./feeds/luci/applications/luci-app-smartdns
        git clone https://github.com/pymumu/openwrt-smartdns ./feeds/packages/net/smartdns
        git clone https://github.com/pymumu/luci-app-smartdns ./feeds/luci/applications/luci-app-smartdns/

        ./scripts/feeds install -a
        # ./scripts/feeds install -a -f

    - name: Post-feeds
      working-directory: ./openwrt
      run : |
        git checkout ${{env.tag}}

        sed -i '/DEFAULT:=n/d' ./feeds/packages/net/rp-pppoe/Makefile
        # sed -i 's/LOG info "Check/#LOG info "Check/' ./feeds/packages/net/mwan3/files/usr/sbin/mwan3track

        mkdir -p ./files/etc/uci-defaults
        mkdir -p ./files/usr/bin
        gost=$(curl -s https://api.github.com/repos/go-gost/gost/releases/latest | jq -r '.tag_name' | sed 's/^v//')
        curl -Lso /tmp/gost.tar.gz https://github.com/go-gost/gost/releases/download/v${gost}/gost_${gost}_linux_amd64v3.tar.gz
        tar xzf /tmp/gost.tar.gz -C /tmp
        mv /tmp/gost ./files/usr/bin/gost
        echo chmod +x /usr/bin/gost > ./files/etc/uci-defaults/99-gost

    - name: Generate configuration file
      working-directory: ./openwrt
      run : |
        git checkout ${{env.tag}}
        ver=$(echo ${{env.tag}} | cut -c 2-)
        rm -f ./.config*
        curl -Ls https://downloads.openwrt.org/releases/$ver/targets/x86/64/config.buildinfo | grep -e CONFIG_TARGET_ -e CONFIG_KERNEL_ -e CONFIG_PACKAGE_ -e CONFIG_VERSION_ >> ./.config

        make defconfig

    - name: Build firmware
      working-directory: ./openwrt
      run : |
        git checkout ${{env.tag}}
        make -j$(nproc) || make -j1 V=s

    - name: Prepare artifact
      working-directory: ./openwrt
      run : |
        mkdir -p ./artifact/buildinfo
        mkdir -p ./artifact/firmware
        mkdir -p ./artifact/package
        cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
        rm -rf $(find ./bin/targets/ -type d -name "packages")
        cp -rf $(find ./bin/targets/ -type f) ./artifact/firmware/
        # rm -rf $(find ./artifact/firmware/ -type f -name "*.tar.gz")
        rm -rf $(find ./artifact/firmware/ -type f -name "*.bin")
        rm -rf $(find ./artifact/firmware/ -type f -name "*.img*" | grep -v "combined-efi")
        cp -rf $(find ./ -type f -regex '.*\.\(ipk\|apk\)$') ./artifact/package/

    - name: Deliver buildinfo
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_buildinfo_${{env.tag}}_${{env.date}}
        path: ./openwrt/artifact/buildinfo/

    - name: Deliver firmware
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_firmware_${{env.tag}}_${{env.date}}
        path: ./openwrt/artifact/firmware/

    - name: Deliver package
      uses: actions/upload-artifact@v4
      with:
        name: OpenWrt_package_${{env.tag}}_${{env.date}}
        path: ./openwrt/artifact/package/
